# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b35722abf744a760ed095fcbc5fdb8b494da7b10a9f6a449915c2aba1f2e3788c50d4da11b53bd1b2ef7560a54fb760e51bec2697457e18399b178bdf241be93

test:
  secret_key_base: e6d785f31d922fe5d31c7f54ecf81c9485477499611c2a679e82ebcba553aa52c0935da089853bf22f519f2f4375a319a02aaafa78ff66da5e8c1eec89eaff3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
